### PR TITLE
ClientBootstrap: allow binding sockets

### LINKED ISSUE #1484: Binding ClientBootstrap to a specific Interface
### Expected behavior
_I want to bind a client socket to a particular interface._

### Actual behavior
_Currently ClientBootstrap doesn't provide any options to do so._

### Steps to reproduce

1. Create a ClientBootstrap object
2. try to bind the channel in channelInitializer

### SwiftNIO version/commit hash : 2.16.0
Tag: _2.16.0_
Commit hash: _e876fb37410e0036b98b5361bb18e6854739572b_

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
Target: x86_64-apple-darwin19.4.0
Darwin Bikramjeets-MacBook-Pro.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by weissi**
### Motivation:

It can be useful to `bind` client sockets as well but previously NIO wasn't allowing you to do that.

### Modifications:

Add `ClientBootstrap.bind` which allows you to `bind` sockets.

### Result:

- fixes #1484

### CODE REVIEW

**Comment by weissi** [comment]
@Lukasa not 100% sure what you're proposing. Do you want this to wait until for #1487 ?

**Comment by Lukasa** [comment]
I'm proposing just call `bind` in the channels constructed by the `HappyEyeballsConnector`. Yeah, a bunch of those binds will cause subsequent `connect`s to fail, but only until we do #1487. That lets us throw away _loads_ of code in this PR, that we'll only want to throw away when #1487 lands.

**Comment by weissi** [comment]
@Lukasa won't that delay IPv4 a little bit?

**Comment by weissi** [comment]
@Lukasa hang on, also the `bind` will fail because we'd try to bind the same address/port/family

**Comment by Lukasa** [comment]
Ugh damnit. Yeah, the only way around this is to modify this so that instead of binding a local address you specify a local interface. Not an easy path to go down.

**Comment by weissi** [comment]
> If the user wants to bind a specific address _and port_, then there are very limited options for us. We can try to connect sequentially, but right now if they do that they will get the same behaviour as SadEyeballs (albeit with more work).

@Lukasa  Ah, so the idea is that say we bind to `127.0.0.1:11111` but connect to `localhost:22222`. Then HE may first give us a `Channel` to connect to `[::1]:22222` which we would then try to `bind` to `127.0.0.1:11111`. This would result in `EAFNOSUPPORT` (`Address family not supported by protocol family`) and we'd stop. Subsequently, HE would make us make a channel for `127.0.0.1:22222` which again we'd bind to `127.0.0.1:11111` which then could succeed.

Is that what you're thinking? I think I could buy into this. The delay that HE gives us for IPv4 could be slightly annoying here but I think that's okay because most users who want to `bind` would connect to an IP anyway, so there won't be any resolving going on and therefore no HE either.

**Comment by Lukasa** [comment]
Yes, that’s exactly what I’m thinking.

**Comment by weissi** [comment]
@Lukasa let's do it!

File: Sources/NIO/SadEyeballs.swift [hunk 1]
```diff
@@ -0,0 +1,119 @@
+//===----------------------------------------------------------------------===//
```
Comment (Lukasa) [inline Sources/NIO/SadEyeballs.swift:1]: Didn't we kill this whole file?

Comment (weissi) [reply Sources/NIO/SadEyeballs.swift:1]: whooooops, yes

Comment (weissi) [reply Sources/NIO/SadEyeballs.swift]: great catch, fixed
