### PR TITLE
Close channel during upgrade, if client closes input

### LINKED ISSUE #2742: NIOTypedWebSocketServerUpgrader hangs when connection is opened and closed without sending any data
### Expected behavior
Given a server setup with WebSocket upgrade using `NIOTypedWebSocketServerUpgrader` and `allowRemoteHalfClosure` set to true on the childChannel. If I open a connection to this server and close it immediately without sending any data the negotiation future returned from `configureUpgradableHTTPServerPipeline` on the server should throw an connection closed error.

### Actual behavior

The negotiation future never completes leaving the child channel open.

If `allowRemoteHalfClosure` is set to false on the server then the negotiation future throws a `inappropriateOperationForState` error which isn't ideal but at least I can catch that the client has closed the connection 

### Steps to reproduce

1. Using the NIOWebSocketServer.swift example
2. Add `.childChannelOption(ChannelOptions.allowRemoteHalfClosure, value: true)` before `bind` call in `run`
3.  Use a client to connect and close connection immediately
```swift
try await ClientBootstrap(group: MultiThreadedEventLoopGroup.singleton)
    .connect(host: "localhost", port: 8888)
    .flatMap { $0.close() }
    .get()
```
4. Note that negotiation future never completes

### SwiftNIO version/commit hash

e5a216ba89deba84356bad9d4c2eab99071c745b

### System & version information

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: x86_64-apple-macosx14.0

### PR DESCRIPTION
**Pull request by adam-fowler**
Check for half closure during server upgrade and close channel if client closes the channel

### Motivation:

This is to fix #2742 

### Modifications:

Add `userInboundEventTriggered` function to `NIOTypedHTTPServerProtocolUpgrader` which checks for `ChannelEvent.inputClosed`

### Result:

Negotiation future now errors when client closes the connection instead of never completing

### CODE REVIEW

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift [hunk 1]
```diff
@@ -152,6 +152,17 @@ public final class NIOTypedHTTPServerUpgradeHandler<UpgradeResult: Sendable>: Ch
         }
     }
 
+    public func userInboundEventTriggered(context: ChannelHandlerContext, event: Any) {
+        switch event {
+        case let evt as ChannelEvent where evt == ChannelEvent.inputClosed:
+            // The remote peer half-closed the channel during the upgrade so we should close
+            context.close(promise: nil)
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift:159]: Thanks for working on this!

Can we please go through the state machine here. In particular, if we are in the state unbuffering we should not close here but rather just hold the event until the unbuffering is done.

Can we also write a test for this and look if we need to do the same for the client upgrade handler?

Comment (Lukasa) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift:159]: We should also consider only closing if we haven't received a full upgrade request, and otherwise we should buffer this.

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift [hunk 2]
```diff
@@ -382,5 +382,23 @@ struct NIOTypedHTTPServerUpgraderStateMachine<UpgradeResult> {
...
+    @usableFromInline
+    enum CloseInboundAction {
+        case close
+        case `continue`
+    }
+
+    @inlinable
+    mutating func closeInbound() -> CloseInboundAction {
+        switch self.state {
+        case .initial, .awaitingUpgrader:
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift:394]: We should immediately close in the state `initial`. In the state `awaitingUpgrader` we have to check if we have `seenFirstRequest == true`. If have seen that we should buffer the `inputClosed` and send it after the upgrading is finished. In the state `upgraderReady` we need to buffer the `inputClosed` indefinitely.

The reason why this is so complicated is that the client could potentially send a half closure after it send the initial upgrade request + some data on the upgraded protocol. We can't just unconditionally close here but we rather need to buffer the `inputClose` and unbuffer it with the data. I would recommend changing the `var buffer: Deque<NIOAny>` in the various states to `var buffer: Deque<enum(NIOAny | inputClosed)>`.

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift [hunk 3]
```diff
@@ -382,5 +382,23 @@ struct NIOTypedHTTPServerUpgraderStateMachine<UpgradeResult> {
...
+            self.state = .finished
+            return .close
+
+        default:
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift:398]: Can we please spell out all cases explicitly so if we ever add one we get a compiler error here

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift (hunk 1 above)
Comment (FranzBusch) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift]: It should be possible to emulate half closure with the embedded channel by just sending the event to the channel.

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift (hunk 2 above)
Comment (adam-fowler) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift]: Done!

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift [hunk 4]
```diff
@@ -382,5 +392,49 @@ struct NIOTypedHTTPServerUpgraderStateMachine<UpgradeResult> {
...
+            return .close
+
+        case .awaitingUpgrader(var awaitingUpgrader):
+            if awaitingUpgrader.seenFirstRequest {
+                // We should buffer the input close since we have seen the full request.
+                awaitingUpgrader.buffer.append(.inputClosed)
+                self.state = .awaitingUpgrader(awaitingUpgrader)
+                return .continue
+            } else {
+                // We shouldn't buffer. This means we are still expecting HTTP parts.
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift:415]: NIT
```suggestion
                // We shouldn't buffer. This means we were still expecting HTTP parts.
```

File: Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift [hunk 5]
```diff
@@ -2066,5 +2073,31 @@ final class TypedHTTPServerUpgradeTestCase: HTTPServerUpgradeTestCase {
         // We also want to confirm that the upgrade handler is no longer in the pipeline.
         try connectedServer.pipeline.waitForUpgraderToBeRemoved()
     }
+
+    func testHalfClosure() throws {
```
Comment (FranzBusch) [inline Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift:2077]: Can we add one or two more tests cases here:
1. That sends the request head then input close
2. That sends a full request head & end and then input close to check that we continue the upgrade

File: Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift [hunk 6]
```diff
@@ -2066,5 +2073,31 @@ final class TypedHTTPServerUpgradeTestCase: HTTPServerUpgradeTestCase {
...
+                case ChannelError.inputClosed:
+                    errorCaught.wrappedValue = true
+                default:
+                    break
+                }
+            }
+        ) { (context) in
+        }
+
+        try client.close().wait()
```
Comment (FranzBusch) [inline Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift:2097]: Is this really testing the half closure here?

File: Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift (hunk 5 above)
Comment (adam-fowler) [reply Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift:2077]: @FranzBusch 
I did 2

I'm not sure what the expected result is for 1
First I had to send a request head that included a content-length so a `.head` would be passed down the pipeline, but not an`.end` eg
```
OPTIONS * HTTP/1.1\r\nHost: localhost\r\ncontent-length: 10\r\nUpgrade: myproto\r\nKafkaesque: yup\r\nConnection: upgrade\r\nConnection: kafkaesque\r\n\r\n
```
With this it gets stuck in the state `.upgradeReady` because nothing else happens after inputClosed to forward the state machine onwards and the connection stays open. If I return `.close` from the state machine everything works but you explicitly said I shouldn't do that.

Comment (adam-fowler) [reply Tests/NIOHTTP1Tests/HTTPServerUpgradeTests.swift:2324]: @FranzBusch any thoughts

**Comment by weissi** [comment]
ping @FranzBusch and @Lukasa

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift [hunk 7]
```diff
@@ -393,5 +403,49 @@ struct NIOTypedHTTPServerUpgraderStateMachine<UpgradeResult> {
...
     }
 
+    @usableFromInline
+    enum CloseInboundAction {
+        case close
+        case `continue`
+    }
+
+    @inlinable
+    mutating func closeInbound() -> CloseInboundAction {
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift:413]: Naming NIT: Can we call this `inputClosed` instead please

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift [hunk 8]
```diff
@@ -393,5 +403,49 @@ struct NIOTypedHTTPServerUpgraderStateMachine<UpgradeResult> {
...
+            self.state = .upgraderReady(upgraderReady)
+            return .continue
+
+        case .unbuffering(var unbuffering):
+            unbuffering.buffer.append(.inputClosed)
+            self.state = .unbuffering(unbuffering)
+            return .continue
+
+        case .modifying, .finished:
+            return .continue
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift:446]: In finished we should forward the `inputClosed` event. In `modifying` we should `fatalError` as we do in the other methods.

**Review by FranzBusch — COMMENTED** [review]
Sorry for the delay. We are really close here. Just a few last comments

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift (hunk 7 above)
Comment (adam-fowler) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift]: done

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift (hunk 8 above)
Comment (adam-fowler) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift]: done

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift [hunk 9]
```diff
@@ -379,8 +385,12 @@ struct NIOTypedHTTPServerUpgraderStateMachine<UpgradeResult> {
 
             if let element = unbuffering.buffer.popFirst() {
                 self.state = .unbuffering(unbuffering)
-
-                return .fireChannelRead(element)
+                switch element {
+                case .data(let data):
+                    return .fireChannelRead(data)
+                case .inputClosed:
+                    return .close
```
[the remark this answers is not in the document]
Comment (adam-fowler) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgraderStateMachine.swift]: done

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift [hunk 10]
```diff
@@ -154,6 +154,25 @@ public final class NIOTypedHTTPServerUpgradeHandler<UpgradeResult: Sendable>: Ch
...
     }
 
+    public func userInboundEventTriggered(context: ChannelHandlerContext, event: Any) {
+        switch event {
+        case let evt as ChannelEvent where evt == ChannelEvent.inputClosed:
+            // The remote peer half-closed the channel during the upgrade. Should we close the other side
+            switch self.stateMachine.inputClosed() {
+            case .close:
+                self.upgradeResultPromise.fail(ChannelError.inputClosed)
+                context.close(promise: nil)
```
Comment (FranzBusch) [inline Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift:164]: Can we switch these two lines around so we first call close and then fulfil the promise. This should avoid potential bugs where the promise callbacks interact with the channel.

**Review by FranzBusch — COMMENTED** [review]
This looks great. One last small comment!

File: Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift (hunk 10 above)
Comment (adam-fowler) [reply Sources/NIOHTTP1/NIOTypedHTTPServerUpgradeHandler.swift]: done

**Review by FranzBusch — APPROVED** [review]
Great! Thanks for working on this.
