### PR TITLE
Fixes build issue on 4.1

### LINKED ISSUE #228: Swift Build warnings in 4.1
### Expected behavior
Build to complete successfully without any warnings

### Actual behavior

```
App/.build/checkouts/swift-nio.git-3108475404973543938/Sources/NIO/System.swift:60:112: warning: using '!' in this location is deprecated and will be removed in a future release; consider changing this to '?' instead
private let sysInet_ntop: @convention(c) (CInt, UnsafeRawPointer?, UnsafeMutablePointer<CChar>?, socklen_t) -> UnsafePointer<CChar>! = inet_ntop
                                                                                                               ^                   ~
                                                                                                                                   ?
```

### Steps to reproduce

1. Build NIO in Xcode 9.3 Beta 4

### SwiftNIO version/commit hash

1.3.0

### Swift & OS version (output of `swift --version && uname -a`)

```
$  swift --version && uname -a
Apple Swift version 4.1 (swiftlang-902.0.43 clang-902.0.37.1)
Target: x86_64-apple-darwin17.4.0
Darwin Tims-MBP.home 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by 0xTim**
Fix build warning in library and build error in WebSocketServer when building with Swift 4.1

### Motivation:

Resolves #228 

### Modifications:

Remove type information in empty closure fixed build warning with compiler suggestion

### Result:

No API changes, no issues building on 4.1!

### CODE REVIEW

File: Sources/NIOWebSocketServer/main.swift [hunk 1]
```diff
@@ -145,7 +145,7 @@ private final class WebSocketTimeHandler: ChannelInboundHandler {
         buffer.write(string: "\(theTime)")
 
         let frame = WebSocketFrame(fin: true, opcode: .text, data: buffer)
-        ctx.writeAndFlush(self.wrapOutboundOut(frame)).map { (_: Void) in
+        ctx.writeAndFlush(self.wrapOutboundOut(frame)).map { _ in
```
Comment (Lukasa) [inline Sources/NIOWebSocketServer/main.swift]: Let's not explicitly ignore the parameter: that's unsafe if we ever changed the return value of this future. Let's just do `{` instead.

**Comment by Lukasa** [comment]
@swift-nio-bot test this please
