### PR TITLE
Prevent spurious test failure in testShuttingDownFailsRegistration

### LINKED ISSUE #333: EventLoopTest.testShuttingDownFailsRegistration shouldn't fail
### Expected behavior
`EventLoopTest.testShuttingDownFailsRegistration` should be stable and not randomly fail.

### Actual behavior

```
18:32:26 Test Case 'EventLoopTest.testShuttingDownFailsRegistration' started at 2018-04-18 17:32:26.373
18:32:26 /code/Tests/NIOTests/EventLoopTest.swift:192: error: EventLoopTest.testShuttingDownFailsRegistration : XCTAssertFalse failed - 
18:32:26 Test Case 'EventLoopTest.testShuttingDownFailsRegistration' failed (0.007 seconds)
```

from here: https://ci.swiftnio.io:4433/job/swift-nio-master/195/console

### Steps to reproduce

dunno, run test in a loop on Linux?

### If possible, minimal yet complete reproducer code (or URL to code)

test should be fairly minimal

### SwiftNIO version/commit hash

9360bd5c4940f61f301e71497606ec853efa2a8d

### Swift & OS version (output of `swift --version && uname -a`)

CI, Swift 4.0.3

### PR DESCRIPTION
**Pull request by Lukasa**
Motivation:

There were two errors in testShuttingDownFailsRegistration that
could cause spurious test failures.

The first was that the test did not wait for connection establishment
before it began shutting the selector down, due to a change made in

The second was that the server side of the connection was not wedged open,
and so it would be closed by the call to loop.closeGently. That closure
could, if the main thread took long enough, lead to the client side
reading EOF and being forcibly closed.

Modifications:

Added a promise to wait for connection establishment.
Added support for wedging both the server and client side open.

Result:

Fewer test failures.

Resolves #333.

### CODE REVIEW

**Comment by weissi** [comment]
@swift-nio-bot test this please

**Comment by weissi** [comment]
(both builds timed out)

File: Tests/NIOTests/EventLoopTest.swift [hunk 1]
```diff
@@ -130,20 +130,31 @@ public class EventLoopTest : XCTestCase {
...
+                XCTAssertTrue(ctx.channel.isActive)
                 self.closePromise = ctx.eventLoop.newPromise()
                 self.closePromise!.futureResult.whenSuccess {
                     ctx.close(mode: mode, promise: promise)
                 }
+                promiseRegisterCallback(self.closePromise!)
             }
         }
 
+        let promiseQueue = DispatchQueue(label: "promisequeue")
```
Comment (normanmaurer) [inline Tests/NIOTests/EventLoopTest.swift]: nit: s/promisequeue/promiseQueue/ ?

File: Tests/NIOTests/EventLoopTest.swift [hunk 2]
```diff
@@ -156,23 +167,33 @@ public class EventLoopTest : XCTestCase {
...
+            }
+            .bind(host: "127.0.0.1", port: 0).wait()
         defer {
             XCTAssertNoThrow(try serverChannel.syncCloseAcceptingAlreadyClosed())
         }
+        let connectPromise: EventLoopPromise<Void> = loop.newPromise()
 
         // We're going to create and register a channel, but not actually attempt to do anything with it.
-        let wedgeHandler = WedgeOpenHandler()
+        let wedgeHandler = WedgeOpenHandler { promise in promiseQueue.sync { promises.append(promise) } }
```
Comment (normanmaurer) [inline Tests/NIOTests/EventLoopTest.swift]: nit: I like the formatting here more in terms of readability:

https://github.com/apple/swift-nio/pull/338/files#diff-6e227f3a42e326a8e6c1dc8acdd423e7R172

**Comment by Lukasa** [comment]
Addressed.

**Comment by Lukasa** [comment]
@weissi Mind re-reviewing this for me?
