### PR TITLE
Also collect total bytes allocated in alloc tests #1115

### LINKED ISSUE #1115: Alloc counter tests to also gather "total bytes" allocated
### Expected behavior
The number of malloc/free calls is very useful, and good to check regressions.

We would also want to check how much memory is allocated though, more for cases about learning about the footprint of specific use case than setting a hard limit on it though.

### Actual behavior

Actual nr. of allocated bytes is not tracked.

I can provide a PR for this in a bit, as I had it modified for some of my experimentation work recently.

### PR DESCRIPTION
**Pull request by ktoso**
Motivation:

It is useful/interesting to have an overview about total bytes
allocated, not only the number of malloc calls.

This is not used to fail tests though, more as an informational thing.

Modifications:

Introduce and hit new counter with allocated size whenever allocations
happen.

Result:

- It is possible to inspect the total allocated bytes.
- Resolves #1115

### CODE REVIEW

**Comment by ktoso** [comment]
Though it can be debated if / how / when / where such counting should take place.
I had a need to write such tests to inspect some things, and either we'll end up having the mini framework copied or we can push these upstream... 

One could argue that those counters are more interesting "development time", though then the question remains where and how to insert them when I want to explore memory footprint etc. 🤔

File: IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh [hunk 1]
```diff
@@ -24,8 +24,10 @@ function die() {
 
 function make_git_commit_all() {
     git init > /dev/null
-    git config --local user.email does@really-not.matter
-    git config --local user.name 'Does Not Matter'
+    if [[ "$(git config user.email)" == ""]]; then
+        git config --local user.email does@really-not.matter
+        git config --local user.name 'Does Not Matter'
+    fi
```
Comment (ktoso) [inline IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh]: matters if someone (me) has globally configured "always sign all commits"

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h [hunk 2]
```diff
@@ -22,4 +22,8 @@ void inc_malloc_counter(void);
 void reset_malloc_counter(void);
 long read_malloc_counter(void);
 
+void add_malloc_bytes_counter(int v);
```
Comment (Lukasa) [inline IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: This function doesn't exist: `MAKE_COUNTER` doesn't define an `add_counter` function and you haven't extended the macro to use this, so I suspect this would fail to link.

Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: Right, sorry; sloppy copy-pasta-ing; In general, we happy to merge such new counter?

Comment (Lukasa) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: @weissi owns this mostly. I don't care, but he may care.

File: IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh [hunk 3]
```diff
@@ -24,8 +24,10 @@ function die() {
 
 function make_git_commit_all() {
     git init > /dev/null
-    git config --local user.email does@really-not.matter
-    git config --local user.name 'Does Not Matter'
+    if [[ "$(git config user.email)" == ""]]; then
```
Comment (weissi) [inline IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh]: nit, space missing before `]]`

File: IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh (hunk 1 above)
Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh]: haha sorry :)

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h (hunk 2 above)
Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: I'm happy with that. But the type should match `malloc`'s argument and be `size_t`.

File: IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh (hunk 1 above)
Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh]: :)

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h (hunk 2 above)
Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: Right, thanks :) Sorry for the messy PR, should have vetted my hacky thing before I cherry picked it over

File: IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh (hunk 3 above)
Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/run-allocation-counter.sh]: THanks :)

**Comment by ktoso** [comment]
Comments addresed, sorry that was a bit messy; thanks for accepting, will make my life a bit simpler :)

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c [hunk 4]
```diff
@@ -20,6 +20,9 @@
 */    atomic_fetch_add_explicit(&g_ ## name ## _counter, 1, memory_order_relaxed); /*
 */ } /*
 */ /*
+*/ void add_ ## name ## _counter(int v) { /*
```
Comment (weissi) [inline IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: @ktoso this still uses `int` but it needs to use either `int` or `size_t` I think. We could fix  `MAKE_COUNTER` like `#define MAKE_COUNTER(_type, _name) ...`. The other option would probably be to make everything `ssize_t` or something but that's a bit annoying as we'd get some signed/unsigned conversions.

Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: actually making everything `intptr_t` might be the right call. That matches Swift's `Int` which is the type that we propagate to the user in Swift.

Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: Is changing int here to `size_t` good enough?

Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: @ktoso `size_t` is unsigned

Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: Right; summing up though, those to become accepting `size_t` then and we're good...?

Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: @ktoso if we have one type for all, it has to be `intptr_t`, right? In the overridden `malloc` function we then need to do the (explicit) cast.

Comment (Lukasa) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: Or `ssize_t`?

Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: wanted to match `Swift.Int` as closely as possible. Pretty much all platforms that matter have pointer size == word size so `intptr_t` is kinda good. Exceptions are `x32` and Watch Series 4 and maybe WoW64?

Comment (ktoso) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/src/atomic-counter.c]: Sounds like `intptr_t` it is then; I'll check that tomorrow and check why CI failed. 
Sorry for being slow here

**Comment by ktoso** [comment]
Sorry for delay, will get back to this today or tomorrow

**Comment by weissi** [comment]
friendly ping @ktoso

**Comment by ktoso** [comment]
Whoa that's been a long "tomorrow" :-/

To conclude https://github.com/apple/swift-nio/pull/1116#discussion_r315679328 , the type should be `intptr_t` then? I'll make the change.

Terribly sorry for leaving it hanging such long time

**Comment by weissi** [comment]
@ktoso don't apologise! I'm happy with `intptr_t` or `uintptr_t`, whatever is easiest for you.

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h [hunk 5]
```diff
@@ -22,7 +22,7 @@ void inc_malloc_counter(void);
 void reset_malloc_counter(void);
 long read_malloc_counter(void);
 
-void add_malloc_bytes_counter(size_t v);
+void add_malloc_bytes_counter(intptr_t v);
 void reset_malloc_bytes_counter(void);
 long read_malloc_bytes_counter(void);
```
Comment (ktoso) [inline IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: I think that's what you meant in https://github.com/apple/swift-nio/pull/1116/files#r315248349 @weissi ?
Please sanity check, I'm not 100% sure that's right.

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h [hunk 6]
```diff
@@ -22,4 +22,8 @@ void inc_malloc_counter(void);
 void reset_malloc_counter(void);
 long read_malloc_counter(void);
 
+void add_malloc_bytes_counter(intptr_t v);
+void reset_malloc_bytes_counter(void);
+long read_malloc_bytes_counter(void);
```
Comment (weissi) [inline IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: there's a `long` here that wants to be `intptr_t` I think.

**Comment by weissi** [comment]
@ktoso the integration tests failed. You should be able to run them locally with

    IntegrationTests/run-tests -d -f allocation

the `-d` enables debug and the `-f` filters out (a regex).

File: IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h (hunk 5 above)
Comment (weissi) [reply IntegrationTests/allocation-counter-tests-framework/template/AtomicCounter/Sources/AtomicCounter/include/atomic-counter.h]: yes, thanks!

**Comment by ktoso** [comment]
Updating branch.

**Comment by weissi** [comment]
@Lukasa ping
