### PR TITLE
channelActive needs to happen before channelRead

### LINKED ISSUE #196: channelRead invoked before channelActive
### Expected behavior

The Channel callbacks lifecycle should start with `channelActive` and end with `channelInactive`.

### Actual behavior

Sometimes under high concurrency the `channelRead` is invoked prior to `channelActive`.

### Steps to reproduce

Run the attached code.

The code fails in one of three ways:

1. It either gets stuck
2. Or it fails with Illegal Instruction on a DispatchQueue (entering some `q.sync`)
3. Or it fails with
```
Precondition failed: channelRead before channelActive!: file StuckTest/RemoteSystem.swift, line 224
Illegal instruction: 4
```

The first two failures might not be relevant, but it warrants to take a look. This particular issue is mainly about failure number 3, Precondition failed.

### Minimal yet complete reproducer code

[StuckTest.zip](https://github.com/apple/swift-nio/files/1827381/StuckTest.zip)

### SwiftNIO version/commit hash

`681ddd8bab4fac997cbc70ca15a1e13c74da50b9` ([nmaurer/order_fix](https://github.com/normanmaurer/swift-nio/tree/order_fix))

### Swift & OS version (output of `swift --version && uname -a`)

Apple Swift version 4.1 (swiftlang-902.0.38 clang-902.0.30)
Target: x86_64-apple-darwin17.4.0
Darwin Levs-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

### PR DESCRIPTION
**Pull request by weissi**
Many thanks for @vlm for the repro! Fixes #196 

Motivation:

`readIfNeeded` was triggered straight after the channel was registered
but _before_ `channelActive` was called which is wrong.

Modifications:

Moved the calls to `readIfNeeded` into `becomeActive0` and removed them
everywhere else (except some error path).

Result:

handle ChannelHandler lifecycle more correctly.

### CODE REVIEW

File: Tests/NIOTests/ChannelTests.swift [hunk 1]
```diff
@@ -1716,4 +1716,89 @@ public class ChannelTests: XCTestCase {
...
+            typealias OutboundOut = ByteBuffer
+
+            private let writeDonePromise: EventLoopPromise<()>
+
+            init(writeDonePromise: EventLoopPromise<()>) {
+                self.writeDonePromise = writeDonePromise
+            }
+
+            func channelActive(ctx: ChannelHandlerContext) {
+                var buffer = ctx.channel.allocator.buffer(capacity: 100)
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: nit: just allocate 4 as this is big enough for "foo" ;)

File: Tests/NIOTests/ChannelTests.swift [hunk 2]
```diff
@@ -1716,4 +1716,89 @@ public class ChannelTests: XCTestCase {
...
+        try sc.pipeline.add(handler: ReadDoesNotHappen(hasRegisteredPromise: clientHasRegistered,
+                                                       hasUnregisteredPromise: clientHasUnregistered)).then {
+                // this will succeed and should not cause the socket to be read even though there'll be something
+                // available to be read immediately
+                sc.register()
+            }.then {
+                // this will fail as the socket is already pre-connected ;)
+                sc.connect(to: bootstrap.localAddress!).map {
+                    XCTFail("should've failed")
+                    }.mapIfError { error in
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: the indention doesn't look right...

File: Tests/NIOTests/ChannelTests.swift (hunk 1 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: but what if it's in UTF-264 encoding that I'll announce tomorrow? :p

fixing :)

File: Tests/NIOTests/ChannelTests.swift [hunk 3]
```diff
@@ -1716,4 +1716,89 @@ public class ChannelTests: XCTestCase {
...
+            }
+            func channelRegistered(ctx: ChannelHandlerContext) {
+                self.hasRegisteredPromise.succeed(result: ())
+            }
+            func channelUnregistered(ctx: ChannelHandlerContext) {
+                self.hasUnregisteredPromise.succeed(result: ())
+            }
+        }
+
+        let elg = MultiThreadedEventLoopGroup(numThreads: 1)
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: also shut this down in a defer block

File: Tests/NIOTests/ChannelTests.swift [hunk 4]
```diff
@@ -1716,4 +1716,92 @@ public class ChannelTests: XCTestCase {
...
+        }
+        let sc = try SocketChannel(eventLoop: elg.next() as! SelectableEventLoop, protocolFamily: AF_INET)
+
+        class WriteImmediatelyHandler: ChannelInboundHandler {
+            typealias InboundIn = Any
+            typealias OutboundOut = ByteBuffer
+
+            private let writeDonePromise: EventLoopPromise<()>
+
+            init(writeDonePromise: EventLoopPromise<()>) {
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: @weissi we usually use `EventLoopPromise<Void>` I think... Not sure what is the "more swifty way tho". Thoughts ?

File: Tests/NIOTests/ChannelTests.swift [hunk 5]
```diff
@@ -1716,4 +1716,92 @@ public class ChannelTests: XCTestCase {
...
+            func channelUnregistered(ctx: ChannelHandlerContext) {
+                self.hasUnregisteredPromise.succeed(result: ())
+            }
+        }
+
+        let elg = MultiThreadedEventLoopGroup(numThreads: 1)
+        defer {
+            XCTAssertNoThrow(try elg.syncShutdownGracefully())
+        }
+        let sc = try SocketChannel(eventLoop: elg.next() as! SelectableEventLoop, protocolFamily: AF_INET)
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: IMHO we use `PF_INET` usually, so maybe change this as well ?

File: Tests/NIOTests/ChannelTests.swift [hunk 6]
```diff
@@ -1716,4 +1716,92 @@ public class ChannelTests: XCTestCase {
...
+            func channelActive(ctx: ChannelHandlerContext) {
+                var buffer = ctx.channel.allocator.buffer(capacity: 4)
+                buffer.write(string: "foo")
+                ctx.writeAndFlush(NIOAny(buffer), promise: self.writeDonePromise)
+            }
+        }
+
+        let serverWriteHappenedPromise: EventLoopPromise<()> = elg.next().newPromise()
+        let clientHasRegistered: EventLoopPromise<()> = elg.next().newPromise()
+        let clientHasUnregistered: EventLoopPromise<()> = elg.next().newPromise()
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: same comment about using `Void` here.

File: Tests/NIOTests/ChannelTests.swift [hunk 7]
```diff
@@ -1716,4 +1716,92 @@ public class ChannelTests: XCTestCase {
...
+
+        let bootstrap = try! ServerBootstrap(group: elg)
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: I think you can remove `!` here.

File: Tests/NIOTests/ChannelTests.swift (hunk 4 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: @normanmaurer for functions that have 'no return value' (sure you _could_ `return ()` but you don't have to) I tend to use `-> Void` but the promises we succeed with the value `()`. Therefore I mostly use `EventLoopPromise<()>` as there is a value 'sent'. Our codebase has both:

```
johannes:~/devel/swift-nio (jw-read-after-active-not-registered)
$ git grep 'EventLoopPromise<Void>' | wc -l
     220
johannes:~/devel/swift-nio (jw-read-after-active-not-registered)
$ git grep 'EventLoopPromise<()>' | wc -l
      57
```

Comment (normanmaurer) [reply Tests/NIOTests/ChannelTests.swift]: @weissi maybe a follow-up but I think w should make it consistent ;) I am not sure what is the "preferred" way tho.

Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: @normanmaurer ok, I'll file an issue.

Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: see #211

File: Tests/NIOTests/ChannelTests.swift (hunk 6 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: #211

File: Tests/NIOTests/ChannelTests.swift [hunk 8]
```diff
@@ -1716,4 +1716,92 @@ public class ChannelTests: XCTestCase {
...
+                    case let e as IOError where e.errnoCode == EISCONN:
+                        // OK
+                        ()
+                    default:
+                        XCTFail("wrong error \(error)")
+                    }
+                }
+            }.wait()
+        try clientHasRegistered.futureResult.wait()
+        try sc.close().wait()
```
Comment (Lukasa) [inline Tests/NIOTests/ChannelTests.swift]: I think this is very slightly probabilistic, as the close can technically race with the return to the selector such that it occurs before the selector is next polled. I think the only way you can avoid this is to connect-and-read-from another channel, which kinda sucks, but may be necessary.

File: Tests/NIOTests/ChannelTests.swift [hunk 9]
```diff
@@ -1716,4 +1716,143 @@ public class ChannelTests: XCTestCase {
...
+            }
+        }
+
+        let group = MultiThreadedEventLoopGroup(numThreads: 2)
+        defer {
+            XCTAssertNoThrow(try group.syncShutdownGracefully())
+        }
+        let serverEL = group.next()
+        let clientEL = group.next()
+        precondition(serverEL !== clientEL)
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: @weissi just make this an `XCTAssertTrue` ?

File: Tests/NIOTests/ChannelTests.swift [hunk 10]
```diff
@@ -1716,4 +1716,143 @@ public class ChannelTests: XCTestCase {
...
+        _ = try sc.selectable.connect(to: bootstrap.localAddress!)
+        let acceptedChannel = try serverWriteHappenedPromise.futureResult.wait()
+        try sc.pipeline.add(handler: ReadDoesNotHappen(hasRegisteredPromise: clientHasRegistered,
+                                                       hasUnregisteredPromise: clientHasUnregistered)).then {
+                // this will succeed and should not cause the socket to be read even though there'll be something
+                // available to be read immediately
+                sc.register()
+            }.then {
+                // this should fail (and will on Darwin but _not_ Linux) as the socket is already pre-connected ;)
+                // on Linux a subsequent connect will just silently succeed, go figure...
```
Comment (normanmaurer) [inline Tests/NIOTests/ChannelTests.swift]: This really makes me sad :( I wonder if there is no other way to test this in a more "consistent" way

File: Tests/NIOTests/ChannelTests.swift (hunk 9 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: the problem is that if I do this, the test would just hang forever if something goes wrong (as `XCTAssert`s trigger _after_ the test has finished)

File: Tests/NIOTests/ChannelTests.swift (hunk 10 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: @normanmaurer after @Lukasa 's patch is in I can create a `Socket` subclass which lets a subsequent 'special' connect succeed on all platforms. That way we can test even more as the channel does become active.

File: Tests/NIOTests/ChannelTests.swift (hunk 9 above)
Comment (normanmaurer) [reply Tests/NIOTests/ChannelTests.swift]: I see... ok

File: Tests/NIOTests/ChannelTests.swift (hunk 10 above)
Comment (normanmaurer) [reply Tests/NIOTests/ChannelTests.swift]: @weissi which patch you are talking about ? :)

File: Tests/NIOTests/ChannelTests.swift (hunk 5 above)
Comment (vlm) [reply Tests/NIOTests/ChannelTests.swift]: `AF_INET` is newer, more standard and overall more preferred. https://stackoverflow.com/questions/6729366/what-is-the-difference-between-af-inet-and-pf-inet-in-socket-programming

File: Tests/NIOTests/ChannelTests.swift [hunk 11]
```diff
@@ -1716,4 +1716,143 @@ public class ChannelTests: XCTestCase {
...
+        }
+
+        let group = MultiThreadedEventLoopGroup(numThreads: 2)
+        defer {
+            XCTAssertNoThrow(try group.syncShutdownGracefully())
+        }
+        let serverEL = group.next()
+        let clientEL = group.next()
+        precondition(serverEL !== clientEL)
+        let sc = try SocketChannel(eventLoop: clientEL as! SelectableEventLoop, protocolFamily: PF_INET)
```
Comment (vlm) [inline Tests/NIOTests/ChannelTests.swift]: I'd prefer `AF_INET`. 2c.

Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: isn't AF address family and PF protocol family?

File: Tests/NIOTests/ChannelTests.swift (hunk 10 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: @normanmaurer I must have dreamt ;)

File: Tests/NIOTests/ChannelTests.swift (hunk 11 above)
Comment (Lukasa) [reply Tests/NIOTests/ChannelTests.swift]: They're the same. There's no meaningful distinction here: the idea that these constants are different is a legacy from a bygone era.

Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: @Lukasa so should I use `PF_INET | AF_INET` :P

Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: @normanmaurer wanted `PF_INET` https://github.com/apple/swift-nio/pull/204#discussion_r176091494 . I don't care :)

File: Tests/NIOTests/ChannelTests.swift [hunk 12]
```diff
@@ -1716,4 +1716,115 @@ public class ChannelTests: XCTestCase {
...
+        _ = try sc.selectable.connect(to: bootstrap.localAddress!)
+        try serverWriteHappenedPromise.futureResult.wait()
+        try sc.pipeline.add(handler: ReadDoesNotHappen(hasRegisteredPromise: clientHasRegistered,
+                                                       hasUnregisteredPromise: clientHasUnregistered,
+                                                       hasReadPromise: clientHasRead)).then {
+                // this will succeed and should not cause the socket to be read even though there'll be something
+                // available to be read immediately
+                sc.register()
+            }.then {
+                // this should fail (and will on Darwin but _not_ Linux) as the socket is already pre-connected ;)
```
Comment (Lukasa) [inline Tests/NIOTests/ChannelTests.swift]: This comment is out of date.

File: Tests/NIOTests/ChannelTests.swift (hunk 11 above)
Comment (normanmaurer) [reply Tests/NIOTests/ChannelTests.swift]: @weissi @Lukasa to be clear I dont care which we use as long as we use it in a consistent way ;) I only suggested PF_INET because we use it in SocketAddress.

File: Tests/NIOTests/ChannelTests.swift (hunk 12 above)
Comment (weissi) [reply Tests/NIOTests/ChannelTests.swift]: thanks, fixed
