### PR TITLE
DatagramChannelTests: Handle receiving datagrams out-of-order in ECN tests

### LINKED ISSUE #2114: Slightly flaky test DatagramChannelTests.testEcnSendReceiveIPV4
Discovered via internal tools

```
Test Suite 'Selected tests' started at 2022-05-13 16:28:40.627
Test Suite 'DatagramChannelTests' started at 2022-05-13 16:28:40.629
Test Case 'DatagramChannelTests.testEcnSendReceiveIPV4' started at 2022-05-13 16:28:40.629
/workspace/.logs/FA64A58E-D8A3-40BE-A7B9-8C06931AD7D6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testEcnSendReceiveIPV4 : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.congestionExperienced)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportNotCapable)") - 
/workspace/.logs/FA64A58E-D8A3-40BE-A7B9-8C06931AD7D6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testEcnSendReceiveIPV4 : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag0)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.congestionExperienced)") - 
/workspace/.logs/FA64A58E-D8A3-40BE-A7B9-8C06931AD7D6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testEcnSendReceiveIPV4 : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag1)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag0)") - 
/workspace/.logs/FA64A58E-D8A3-40BE-A7B9-8C06931AD7D6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testEcnSendReceiveIPV4 : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportNotCapable)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag1)") - 
Test Case 'DatagramChannelTests.testEcnSendReceiveIPV4' failed (0.009 seconds)
Test Suite 'DatagramChannelTests' failed at 2022-05-13 16:28:40.638
	 Executed 1 test, with 4 failures (0 unexpected) in 0.009 (0.009) seconds
Test Suite 'Selected tests' failed at 2022-05-13 16:28:40.638
	 Executed 1 test, with 4 failures (0 unexpected) in 0.009 (0.009) seconds
Command failed reason=exit, status=1
```

### LINKED ISSUE #2122: Slightly flaky test DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite
Discovered via internal tools

```
Test Suite 'Selected tests' started at 2022-05-18 10:45:50.377
Test Suite 'DatagramChannelTests' started at 2022-05-18 10:45:50.379
Test Case 'DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite' started at 2022-05-18 10:45:50.379
/workspace/.logs/14943740-D892-4C3E-9B4A-19E556C750C6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag1)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag0)") - 
/workspace/.logs/14943740-D892-4C3E-9B4A-19E556C750C6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag1)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag0)") - 
/workspace/.logs/14943740-D892-4C3E-9B4A-19E556C750C6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag0)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag1)") - 
/workspace/.logs/14943740-D892-4C3E-9B4A-19E556C750C6/repos/swift-nio/Tests/NIOPosixTests/DatagramChannelTests.swift:723: error: DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite : XCTAssertEqual failed: ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag0)") is not equal to ("Optional(NIOCore.NIOExplicitCongestionNotificationState.transportCapableFlag1)") - 
Test Case 'DatagramChannelTests.testReceiveEcnAndPacketInfoIPV6VectorReadVectorWrite' failed (0.008 seconds)
Test Suite 'DatagramChannelTests' failed at 2022-05-18 10:45:50.387
	 Executed 1 test, with 4 failures (0 unexpected) in 0.008 (0.008) seconds
Test Suite 'Selected tests' failed at 2022-05-18 10:45:50.387
	 Executed 1 test, with 4 failures (0 unexpected) in 0.008 (0.008) seconds
Command failed reason=exit, status=1
```

### PR DESCRIPTION
**Pull request by simonjbeaumont**
### Motivation:

#2114 and #2122 show that the tests that rely on the `testEcnAndPacketInfoReceive(address:vectorRead:vectorSend:receivePacketInfo:)` helper function have false negatives when datagrams are received out-of-order. The tests should be resilient to out-of-order delivery of datagrams.

### Modifications:

Modify the test helper to use an integer payload to associate the reads and writes before comparing the metadata.

### Result:

* Fixes #2114 
* Fixes #2122

### CODE REVIEW

File: Tests/NIOPosixTests/DatagramChannelTests.swift [hunk 1]
```diff
@@ -698,29 +698,39 @@ final class DatagramChannelTests: XCTestCase {
...
-                                                  data: buffer,
-                                                  metadata: .init(ecnState: ecnState, packetInfo: expectedPacketInfo))
+            for (ecnStateIdx, ecnState) in ecnStates.enumerated() {
+                // Datagrams may be received out-of-order, so we use the payload to associate the read.
+                let writeData = AddressedEnvelope(
+                    remoteAddress: receiveChannel.localAddress!,
+                    data: sendChannel.allocator.buffer(
+                        integer: ecnStateIdx,
+                        endianness: .big,
+                        as: Int.self
```
Comment (Lukasa) [inline Tests/NIOPosixTests/DatagramChannelTests.swift:712]: There should be no need for `endianness` or `as` here: the type inference should solve the latter and the default should solve the former.

File: Tests/NIOPosixTests/DatagramChannelTests.swift [hunk 2]
```diff
@@ -698,29 +698,39 @@ final class DatagramChannelTests: XCTestCase {
...
-            for readNumber in 0..<reads.count {
-                let read = reads[readNumber]
-                XCTAssertEqual(read.metadata?.ecnState, ecnStates[readNumber / (vectorSend ? 2 : 1)])
+            let expectedNumReads = ecnStates.count * (vectorSend ? 2 : 1)
+            let reads = try receiveChannel.waitForDatagrams(count: expectedNumReads)
+            XCTAssertEqual(reads.count, expectedNumReads)
+            for read in reads {
+                // Datagrams may be received out-of-order, let's find the associated ecnStateIdx.
+                let ecnStateIdx = try XCTUnwrap(read.data.getInteger(
+                    at: 0,
```
Comment (Lukasa) [inline Tests/NIOPosixTests/DatagramChannelTests.swift:729]: Prefer `at: read.data.readerIndex`.

File: Tests/NIOPosixTests/DatagramChannelTests.swift [hunk 3]
```diff
@@ -698,29 +698,39 @@ final class DatagramChannelTests: XCTestCase {
...
+                    endianness: .big,
```
Comment (Lukasa) [inline Tests/NIOPosixTests/DatagramChannelTests.swift:730]: Here we can remove `endianness`.

File: Tests/NIOPosixTests/DatagramChannelTests.swift (hunk 1 above)
Comment (simonjbeaumont) [reply Tests/NIOPosixTests/DatagramChannelTests.swift]: Was just being paranoid so that I was guaranteeing the same format on the read- and write-paths.

Simplified in 797805d27.

File: Tests/NIOPosixTests/DatagramChannelTests.swift (hunk 2 above)
Comment (simonjbeaumont) [reply Tests/NIOPosixTests/DatagramChannelTests.swift]: 👍 797805d27.

File: Tests/NIOPosixTests/DatagramChannelTests.swift (hunk 3 above)
Comment (simonjbeaumont) [reply Tests/NIOPosixTests/DatagramChannelTests.swift]: 👍 797805d27.

**Review by Lukasa — COMMENTED** [review]
Sorry, one more extended suggestion just to cover our backs.

File: Tests/NIOPosixTests/DatagramChannelTests.swift [hunk 4]
```diff
@@ -698,29 +698,31 @@ final class DatagramChannelTests: XCTestCase {
...
-                XCTAssertEqual(read.metadata?.ecnState, ecnStates[readNumber / (vectorSend ? 2 : 1)])
+            let expectedNumReads = ecnStates.count * (vectorSend ? 2 : 1)
+            let reads = try receiveChannel.waitForDatagrams(count: expectedNumReads)
+            XCTAssertEqual(reads.count, expectedNumReads)
+            for read in reads {
+                // Datagrams may be received out-of-order, let's find the associated ecnStateIdx.
+                let ecnStateIdx: Int = try XCTUnwrap(read.data.getInteger(at: read.data.readerIndex))
+                XCTAssertEqual(read.metadata?.ecnState, ecnStates[ecnStateIdx])
                 XCTAssertEqual(read.metadata?.packetInfo, expectedPacketInfo)
             }
```
[the remark this answers is not in the document]
Comment (simonjbeaumont) [reply Tests/NIOPosixTests/DatagramChannelTests.swift:732]: OK, I changed the test to iterate through what we expect to receive instead of iterating through what we do receive which I think gets the semantics you were after without too much duplication. d63144d3d.

File: Tests/NIOPosixTests/DatagramChannelTests.swift [hunk 5]
```diff
@@ -698,30 +698,37 @@ final class DatagramChannelTests: XCTestCase {
...
-            for readNumber in 0..<reads.count {
-                let read = reads[readNumber]
-                XCTAssertEqual(read.metadata?.ecnState, ecnStates[readNumber / (vectorSend ? 2 : 1)])
-                XCTAssertEqual(read.metadata?.packetInfo, expectedPacketInfo)
+            let expectedNumReads = ecnStates.count * (vectorSend ? 2 : 1)
+            let reads = try receiveChannel.waitForDatagrams(count: expectedNumReads)
+            XCTAssertEqual(reads.count, expectedNumReads)
+            for (ecnStateIdx, ecnState) in ecnStates.enumerated() {
+                // Datagrams may be received out-of-order, let's find the associated reads.
+                let encStateReads = reads.filter { read in
```
Comment (Lukasa) [inline Tests/NIOPosixTests/DatagramChannelTests.swift:724]: Rather than this, can I suggest that we `map` the `reads` into an `Array` of `(ecnStateIdx, metadata)` and then sort it by `ecnStateIdx`? We should then be able to just compare for equality.

Comment (simonjbeaumont) [reply Tests/NIOPosixTests/DatagramChannelTests.swift:724]: We'll then still need to check that each `ecnStateIdx` is seen the expected number of times (depending on `vectorSend`) though? I guess I could build a dictionary of type `[ecnStateIdx: [metadata]]` and check that all the values have the expected length but I'm concerned that this would read less clearly than the code below.

Is the concern the performance off this test or the readability?

Comment (Lukasa) [reply Tests/NIOPosixTests/DatagramChannelTests.swift:724]: We shouldn't need to check the number of times: as `ecnStateIdx` is in the array, the equality check does that for us. My concern is principally the readability: I think as written it is not clear that this test is attempting to confirm that we got the same data going in and coming out. The easiest way to confirm that is to take the reads and transform them into the same state we sent them in.

Comment (simonjbeaumont) [reply Tests/NIOPosixTests/DatagramChannelTests.swift]: 👌 How about 5122d9efb, then?

File: Tests/NIOPosixTests/DatagramChannelTests.swift [hunk 6]
```diff
@@ -698,31 +698,36 @@ final class DatagramChannelTests: XCTestCase {
...
             }
 
-            let expectedReads = ecnStates.count * (vectorSend ? 2 : 1)
-            let reads = try receiveChannel.waitForDatagrams(count: expectedReads)
-            XCTAssertEqual(reads.count, expectedReads)
-            for readNumber in 0..<reads.count {
-                let read = reads[readNumber]
-                XCTAssertEqual(read.metadata?.ecnState, ecnStates[readNumber / (vectorSend ? 2 : 1)])
-                XCTAssertEqual(read.metadata?.packetInfo, expectedPacketInfo)
+            let expectedNumReads = ecnStates.count * (vectorSend ? 2 : 1)
```
Comment (Lukasa) [inline Tests/NIOPosixTests/DatagramChannelTests.swift:721]: Nit:

```suggestion
            let expectedNumReads = metadataWrites.count
```

**Review by Lukasa — APPROVED** [review]
Nice!
