### PR TITLE
HappyEyeballs should tolerate uncancellable tasks.

### LINKED ISSUE #187: fatalError() during high concurrency test
### Expected behavior

Users generally expect Swift NIO not to fail with internal assertions and `fatalError`s they couldn't catch.

### Actual behavior

```
Fatal error: Invalid FSM transition attempt: state complete, input connectTimeoutElapsed: file swift-nio/Sources/NIO/HappyEyeballs.swift, line 417
Illegal instruction: 4
```

### Steps to reproduce

Compile and run the attached code against the master.

### If possible, minimal yet complete reproducer code (or URL to code)

[reproduce.swift](https://github.com/apple/swift-nio/files/1823817/reproduce.swift.txt).

### SwiftNIO version/commit hash

b8d883da2c2090d02ec4890b5ab5c7c9bfa30935

### Swift & OS version (output of `swift --version && uname -a`)

```
Apple Swift version 4.1 (swiftlang-902.0.38 clang-902.0.30)
Target: x86_64-apple-darwin17.4.0
Darwin Levs-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by Lukasa**
Motivation:

The HappyEyeballs state machine incorrectly assumed that it would always
be able to cancel any scheduled task that would execute on the event loop
that the state machine itself was running on. This is not accurate: if
the scheduled task is scheduled to execute at roughly the same time as
another callback into the state machine then it may be uncancellable.

Modifications:

Allowed the three scheduled tasks (connect timeout, connect delay, and
resolver delay) to fire in completed.

Result:

No fatalErrors in window conditions under high load

Resolves #187.

### CODE REVIEW

File: Tests/NIOTests/HappyEyeballsTest.swift [hunk 1]
```diff
@@ -1152,6 +1152,104 @@ public class HappyEyeballsTest : XCTestCase {
...
         }
     }
+
+    func testCancellationSyncWithConnectDelay() throws {
+        var channels: [Channel] = []
+        defer {
+            channels.finishAll()
+        }
+
+        let (eyeballer, resolver, loop) = buildEyeballer(host: "example.com", port: 80, connectTimeout: .milliseconds(250)) {
```
Comment (normanmaurer) [inline Tests/NIOTests/HappyEyeballsTest.swift]: @Lukasa maybe we just want to use `swiftnio.io` for the hostname everywhere tho ?

Comment (Lukasa) [reply Tests/NIOTests/HappyEyeballsTest.swift]: I think it doesn't really matter?

Comment (normanmaurer) [reply Tests/NIOTests/HappyEyeballsTest.swift]: Yeah sure it not matters in this test but if we have a domain name we can also just use it and not refer to some random ones. Feel free to ignore tho, I don’t say we need to do it but I think knit is a good thing in general

Comment (vlm) [reply Tests/NIOTests/HappyEyeballsTest.swift]: Actually, an `example.com` is just OK for this purpose, see [rfc2606](https://tools.ietf.org/html/rfc2606).

Comment (normanmaurer) [reply Tests/NIOTests/HappyEyeballsTest.swift]: @vlm TIL ... Thanks!

**Comment by normanmaurer** [comment]
@Lukasa can you rebase and merge ?

**Comment by Lukasa** [comment]
@swift-nio-bot test this please
