### PR TITLE
fix AtomicBox by deprecating it and implementing it with a CAS loop

### LINKED ISSUE #1283: Flaky test: testDescriptionCanBeCalledFromNonEventLoopThreads
Swift 5.0, Ubuntu 18.04

```
while time lldb --batch -o run -o run -o run -o run -o run -o run -o run -o run -o run -o run -o run -o run -o run -o run -o run -k "image list" -k "register read" -k "bt all" -k "exit 134" .build/debug/swift-nioPackageTests.xctest NIOTests.ChannelTests/testDescriptionCanBeCalledFromNonEventLoopThreads; do true; done
```

Head of logs:

```
10:24:39 GitHub pull request #1282 of commit 1a09f85ae3afe317ae4400d605ffaa3e2e237507, no merge conflicts.
10:24:39 Running as SYSTEM
10:24:40 Setting status of 1a09f85ae3afe317ae4400d605ffaa3e2e237507 to PENDING with url https://ci.swiftserver.group/job/swift-nio2-swift50-prb/1289/ and message: 'Build started for merge commit.'
10:24:40 Using context: pull request validation (5.0)
10:24:40 Building remotely on agent 1 in workspace /home/jenkins/workspace/swift-nio2-swift50-prb
10:24:40 Running Prebuild steps
10:24:40 [swift-nio2-swift50-prb] $ /bin/sh -xe /tmp/jenkins2615619674208307922.sh
10:24:40 ++ pwd
10:24:40 ++ id -u
10:24:40 ++ id -g
10:24:40 + docker run --rm -v /home/jenkins/workspace/swift-nio2-swift50-prb:/code -w /code ubuntu:14.04 /bin/bash -lc 'chown -R 1001:1001 /code'
10:24:41 stdin: is not a tty
10:24:42 Success build forhudson.tasks.Shell@68bdc6c8
10:24:42 [ssh-agent] Looking for ssh-agent implementation...
10:24:42 [ssh-agent]   Exec ssh-agent (binary ssh-agent on a remote machine)
10:24:42 $ ssh-agent
10:24:42 SSH_AUTH_SOCK=/tmp/ssh-aMuWGgX15Pq7/agent.12467
10:24:42 SSH_AGENT_PID=12469
10:24:42 [ssh-agent] Started.
10:24:42 Running ssh-add (command line suppressed)
10:24:42 Identity added: /home/jenkins/workspace/swift-nio2-swift50-prb@tmp/private_key_8403194589660431440.key (/home/jenkins/workspace/swift-nio2-swift50-prb@tmp/private_key_8403194589660431440.key)
10:24:42 [ssh-agent] Using credentials swift-nio-bot-deployment-key (swift-nio-bot deployment key)
10:24:42 using credential swift-nio-bot-deployment-key
10:24:42  > git rev-parse --is-inside-work-tree # timeout=10
10:24:42 Fetching changes from the remote Git repository
10:24:42  > git config remote.origin.url git@github.com:apple/swift-nio.git # timeout=10
10:24:42 Fetching upstream changes from git@github.com:apple/swift-nio.git
10:24:42  > git --version # timeout=10
10:24:42 using GIT_SSH to set credentials swift-nio-bot deployment key
10:24:42  > git fetch --tags --progress git@github.com:apple/swift-nio.git +refs/pull/1282/*:refs/remotes/origin/pr/1282/*
10:24:43  > git rev-parse refs/remotes/origin/pr/1282/merge^{commit} # timeout=10
10:24:43  > git rev-parse refs/remotes/origin/origin/pr/1282/merge^{commit} # timeout=10
10:24:43 Checking out Revision d876578552f7efa689a1d528af45c83c57f65194 (refs/remotes/origin/pr/1282/merge)
10:24:43  > git config core.sparsecheckout # timeout=10
10:24:43  > git checkout -f d876578552f7efa689a1d528af45c83c57f65194
10:24:43 Commit message: "Merge 1a09f85ae3afe317ae4400d605ffaa3e2e237507 into 1f94a6e62057745b490e89752a257e2812cd5f26"
10:24:43 First time build. Skipping changelog.
10:24:43 Cleaning workspace
10:24:43  > git rev-parse --verify HEAD # timeout=10
10:24:43 Resetting working tree
10:24:43  > git reset --hard # timeout=10
10:24:43  > git clean -fdx # timeout=10
10:24:43 [swift-nio2-swift50-prb] $ /bin/sh -xe /tmp/jenkins935019229705872663.sh
10:24:43 + docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.50.yaml -p swift-nio2-swift50-prb build
```

Failing test (segv):
```
10:29:43 Test Case 'ChannelTests.testDescriptionCanBeCalledFromNonEventLoopThreads' started at 2019-12-04 10:29:43.886
10:29:44 Exited with signal code 11
10:29:44 Build step 'Execute shell' marked build as failure
```

### LINKED ISSUE #1286: AtomicBox.load() suffers from ABA problem
`AtomicBox.load()` suffers from an ABA problem where the loaded value may be dead before it gets to increase the reference count in

https://github.com/apple/swift-nio/blob/master/Sources/NIOConcurrencyHelpers/atomics.swift#L462-L466

### PR DESCRIPTION
**Pull request by weissi**
Motivation:

Atomic references cannot easily be maintained correctly because the
`load` operation gets a pointer value that might (before the loader gets
a change to retain the returned reference) be destroyed by another
thread.

Modifications:

- Deprecate `AtomicBox`
- Implement `NIOCASLoopBox` with functionality similar to AtomicBox (but
  implemented using a CAS loop :( ).

Result:

- fixes #1286
- fixes #1283

### CODE REVIEW

File: Sources/NIOConcurrencyHelpers/atomics.swift [hunk 1]
```diff
@@ -473,6 +545,17 @@ public final class AtomicBox<T: AnyObject> {
     ///
     /// - Parameter value: The new value to set the object to.
     public func store(_ value: T) -> Void {
```
Comment (drexin) [inline Sources/NIOConcurrencyHelpers/atomics.swift]: This should probably also have the warning about using a CAS loop

Comment (weissi) [reply Sources/NIOConcurrencyHelpers/atomics.swift]: @drexin that one doesn't actually have one though, right?

**Comment by drexin** [comment]
Compilation fails on CI:

```
18:21:28 [9/23] Compiling NIOConcurrencyHelpers atomics.swift
18:21:28 /code/Sources/NIOConcurrencyHelpers/atomics.swift:22:25: error: use of unresolved identifier 'pthread_yield'
18:21:28 let sys_pthread_yield = pthread_yield
18:21:28                         ^~~~~~~~~~~~~
``

**Comment by drexin** [comment]
@weissi Ok, instead of `pthread_yield`, which is non-standard, it should use `sched_yield`

File: Sources/NIOConcurrencyHelpers/atomics.swift (hunk 1 above)
Comment (drexin) [reply Sources/NIOConcurrencyHelpers/atomics.swift]: @weissi It calls `exchange`, which does.

Comment (drexin) [reply Sources/NIOConcurrencyHelpers/atomics.swift]: Oh, I see... it calls it on `storage` directly. Ignore what I said.

File: Sources/NIOConcurrencyHelpers/atomics.swift [hunk 2]
```diff
@@ -458,11 +505,36 @@ public final class AtomicBox<T: AnyObject> {
...
+            }
+        }
+
+        // step 2: We now consumed a +1'd version of val, so we have all the time in the world to retain it.
         let ptr = Unmanaged<T>.fromOpaque(UnsafeRawPointer(bitPattern: ptrBits)!)
-        return ptr.takeUnretainedValue()
+        let value = ptr.takeUnretainedValue()
+
+        // step 3: Now, let's exchange it back into the store
+        if !self.storage.compareAndExchange(expected: 0, desired: ptrBits) {
```
Comment (drexin) [inline Sources/NIOConcurrencyHelpers/atomics.swift]: I think we have an ABA problem here.

T1: load value A (set 0)
T2: store value B (overwrite 0)
T3: load value B (set 0)
T1: write value A back (works because value is 0)
T3: fails to write back value B, because T1 wrote value A back

we just lost the write of value B

Comment (weissi) [reply Sources/NIOConcurrencyHelpers/atomics.swift]: @drexin great catch, you're absolutely right! I thought I'd get away with not doing a CAS loop in `store` but no :).

Comment (weissi) [reply Sources/NIOConcurrencyHelpers/atomics.swift]: @drexin fixed (and tested in `testMultipleLoadsRacingWhilstStoresAreGoingOn`)

File: Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift [hunk 3]
```diff
@@ -750,4 +756,273 @@ class NIOConcurrencyHelpersTests: XCTestCase {
...
+                }
+            }
+        }
+
+        doIt()
+        assert(allDeallocations.load() == iterations + 1, within: .seconds(1))
+    }
+
+    @available(*, deprecated, message: "AtomicBox is deprecated, this is a test for the deprecated functionality")
+    func testMultipleLoadsRacingWhilstStoresAreGoingOn() {
```
Comment (drexin) [inline Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift]: Nice test, but could we make the loading loops use a while loop instead and ensure they actually keep reading until the very end? Currently they could be done much quicker than the writing thread.

Comment (weissi) [reply Tests/NIOConcurrencyHelpersTests/NIOConcurrencyHelpersTests.swift]: good point, done.

File: Sources/NIOConcurrencyHelpers/atomics.swift [hunk 4]
```diff
@@ -389,9 +401,11 @@ extension UInt: AtomicPrimitive {
     public static let atomic_store                = catmc_atomic_unsigned_long_store
 }
 
-/// `AtomicBox` is a heap-allocated box which allows atomic access to an instance of a Swift class.
+/// `AtomicBox` is a heap-allocated box which allows lock-free access to an instance of a Swift class.
 ///
-/// It behaves very much like `Atomic<T>` but for objects, maintaining the correct retain counts.
+/// - warning: The use of `NIOSpinLockBox` should be avoided because it requires an implementation of a spin-lock
```
Comment (Lukasa) [inline Sources/NIOConcurrencyHelpers/atomics.swift]: `NIOSpinLockBox` isn't a type that actually exists.

Comment (weissi) [reply Sources/NIOConcurrencyHelpers/atomics.swift]: ta, fixed
