### PR TITLE
Partial OpenBSD support.

### LINKED ISSUE #3383: BSD support
### Expected behavior
swift-nio builds and is usable on FreeBSD and OpenBSD, especially since FreeBSD is an official platform for Swift 6.2

### Actual behavior

Various build failures, around lock types (`pthread_mutex_t` vs `pthread_mutex_t?`) and `LITTLE_ENDIAN` ifdefs in `c_nio_sha1.c`.

### Steps to reproduce

1. swift build

### If possible, minimal yet complete reproducer code (or URL to code)

n/a

### SwiftNIO version/commit hash

HEAD.

### System & version information

Please provide at the very least your operating system and Swift version
information.

Swift 6.2.0, OpenBSD, but will also likely be a problem on FreeBSD.

### PR DESCRIPTION
**Pull request by 3405691582**
### Motivation:

Additional partial platform support.

### Modifications: 

* Create a new CNIOBSD module for OpenBSD, for general cleanliness, and make use of it throughout. Some of the changes are borrowed directly from CNIOLinux; some may technically be unnecessary; I am erring somewhat on expediency to functionality.

* Since `malloc_size` is unavailable on OpenBSD, and some of the helpers make use of ManagedBufferPointer which makes use of it, mark some of this as unavailable as well.

* Usual pthread optional typing changes, since pthread types are pointers on this platform.

* Add conditionals to exclude other functionality not available here, like IP_RECVPKTINFO or IP_PKTINFO.

* d_ino is a backwards-compatibility macro valued token for dirent, so instead, just expand with a conditional.

* Use kqueue on OpenBSD. This necessitates adding some conditionals for type and feature compatibility.

* The vsock API is unavailable on OpenBSD.

### Result:

Tested the NIOTCPEchoClient and NIOTCPEchoServer appears to work and that swift-nio-ssh (hopefully wlog) builds with a local repository with these changes.

Because NIOFS/_NIOFileSystem depend on some non-portable components, such as extended attributes, sendfile, non-portable linkat flags, and renameat2, this is only just partial OpenBSD support, which means that `swift build` on the full swift-nio project won't build cleanly, but at least the portable parts can be used to build servers and clients. This commit will mark the linked bug as fixed; I will open a new bug for file system support.

Fixes #3383.

### CODE REVIEW

**Comment by rnro** [comment]
Thanks for contributing this and tackling the issue yourself.

File: Sources/CNIOBSD/include/CNIOBSD.h [hunk 1]
```diff
@@ -0,0 +1,77 @@
+//===----------------------------------------------------------------------===//
+//
+// This source file is part of the SwiftNIO open source project
+//
+// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
```
Comment (rnro) [inline Sources/CNIOBSD/include/CNIOBSD.h]: I suspect this should be:
```suggestion
// Copyright (c) 2017-2025 Apple Inc. and the SwiftNIO project authors
```
or even just 2025

**Comment by rnro** [comment]
I haven't performed a full review yet but I think having some very brief documentation of the current status of BSD support would probably be useful.

File: Sources/CNIOBSD/include/CNIOBSD.h [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+#include <fts.h>
+#include <ifaddrs.h>
+#include <net/if.h>
+#include <netinet/in.h>
+#include <netinet/ip.h>
+#include <pthread.h>
+#include <pthread_np.h>
+#include <stdbool.h>
+
+// For context, c.f. comments in CNIOLinux.
```
Comment (rnro) [inline Sources/CNIOBSD/include/CNIOBSD.h]: I think I'd prefer duplicate comments rather than having a reader do a manual diff to find the relevant comments

File: Sources/CNIOBSD/shim.c [hunk 3]
```diff
@@ -0,0 +1,125 @@
+//===----------------------------------------------------------------------===//
+//
+// This source file is part of the SwiftNIO open source project
+//
+// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
```
Comment (rnro) [inline Sources/CNIOBSD/shim.c]:
```suggestion
// Copyright (c) 2017-2025 Apple Inc. and the SwiftNIO project authors
```

File: Sources/CNIOBSD/shim.c [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+// Licensed under Apache License v2.0
+//
+// See LICENSE.txt for license information
+// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
+//
+// SPDX-License-Identifier: Apache-2.0
+//
+//===----------------------------------------------------------------------===//
+
+// For context, c.f. comments in CNIOLinux.
```
Comment (rnro) [inline Sources/CNIOBSD/shim.c]: Similar to elsewhere, let's copy the comments over.

File: Sources/NIOConcurrencyHelpers/atomics.swift [hunk 5]
```diff
@@ -476,6 +476,7 @@ extension UInt: AtomicPrimitive {
     deprecated,
     message: "AtomicBox is deprecated without replacement because the original implementation doesn't work."
 )
+@available(OpenBSD, unavailable, message: "malloc_size is unavailable.")
```
Comment (rnro) [inline Sources/NIOConcurrencyHelpers/atomics.swift:466]: This syntax is new to me, have you confirmed it does what you want?
```
@available(OpenBSD,
```

Comment (3405691582) [reply Sources/NIOConcurrencyHelpers/atomics.swift:466]: Yes. ManagedBufferPointer is unavailable on OpenBSD (see e.g. https://github.com/swiftlang/swift/blob/90e3d1c415412695fe2e5202ae20bf050f98ecd5/stdlib/public/core/ManagedBuffer.swift#L270, which is marked in this same way).

File: Package.swift [hunk 6]
```diff
@@ -163,6 +165,10 @@ let package = Package(
             name: "CNIOSHA1",
             dependencies: []
         ),
+        .target(
+            name: "CNIOBSD",
+            dependencies: [],
```
Comment (rnro) [inline Package.swift]:
```suggestion
            dependencies: []
```

File: Sources/CNIOBSD/include/CNIOBSD.h (hunk 2 above)
Comment (3405691582) [reply Sources/CNIOBSD/include/CNIOBSD.h]: Added the comments back.

File: Sources/CNIOBSD/shim.c (hunk 4 above)
Comment (3405691582) [reply Sources/CNIOBSD/shim.c]: Added the comments back.

**Comment by 3405691582** [comment]
> I haven't performed a full review yet but I think having some very brief documentation of the current status of BSD support would probably be useful.

I added a line in README.md in the section describing platform support.

**Comment by 3405691582** [comment]
Anything else necessary here?

**Review by rnro — APPROVED** [review]
Looks good, thanks

**Comment by Lukasa** [comment]
Hmm, sorry @3405691582 this seems to have gotten stuck. If you can fix up the conflicts we can try to shepherd this through.

**Comment by 3405691582** [comment]
> Hmm, sorry @3405691582 this seems to have gotten stuck. If you can fix up the conflicts we can try to shepherd this through.

I reviewed the conflicting files from the incoming merge and resolved them.

File: Sources/CNIOOpenBSD/include/CNIOOpenBSD.h [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+// Copyright (c) 2017-2025 Apple Inc. and the SwiftNIO project authors
+// Licensed under Apache License v2.0
+//
+// See LICENSE.txt for license information
+// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
+//
+// SPDX-License-Identifier: Apache-2.0
+//
+//===----------------------------------------------------------------------===//
+#ifndef C_NIO_BSD_H
```
Comment (Lukasa) [inline Sources/CNIOOpenBSD/include/CNIOOpenBSD.h]: Given that #3398 is namespacing its header file to FreeBSD, for now let's do the same here and call this CNIOOpenBSD. We can take an action item to dedupe in future if it's useful.

Comment (3405691582) [reply Sources/CNIOOpenBSD/include/CNIOOpenBSD.h]: Done. 

(If we're going to have platform-specific CNIO modules, then I am thinking these should probably be a bit more targeted -- but that's a problem for another day.)

File: Package.swift [hunk 8]
```diff
@@ -59,7 +59,7 @@ let package = Package(
             dependencies: [
                 "NIOConcurrencyHelpers",
                 "_NIOBase64",
-                "CNIOOpenBSD",
+                .target("CNIOOpenBSD", condition: .when(platforms: [.openbsd]),
```
Comment (Lukasa) [inline Package.swift]: Why was this necessary? We should be able to use compiler-defines to enable it to be used on all platforms.

Comment (3405691582) [reply Package.swift]: Checks broke (missing `sys/event.h`). If you'd prefer I wrap the headers in CNIOOpenBSD.h with `#if defined(__OpenBSD__)` I can do that.

Comment (3405691582) [reply Package.swift]: Oh -- as written this won't work anyway, since we don't always have conditional imports, so I have to add the `#if` conditional.

File: Sources/CNIOOpenBSD/include/CNIOOpenBSD.h [hunk 9]
```diff
@@ -0,0 +1,101 @@
...
+// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
+//
+// SPDX-License-Identifier: Apache-2.0
+//
+//===----------------------------------------------------------------------===//
+#ifndef C_NIO_OPENBSD_H
+#define C_NIO_OPENBSD_H
+
+#include <sys/types.h>
+#if defined(__OpenBSD__)
```
Comment (Lukasa) [inline Sources/CNIOOpenBSD/include/CNIOOpenBSD.h:17]: Rather than just guard those out, let's guard out essentially the entire header file.

Comment (3405691582) [reply Sources/CNIOOpenBSD/include/CNIOOpenBSD.h:17]: Done. (I misread the existing style.)

**Comment by rnro** [comment]
I'm sorry, it looks like we're hitting a bunch new compilation failures

**Comment by 3405691582** [comment]
I've rebased atop HEAD and it seems OK to me. I'll double-check on a Linux machine soon and let you know.

**Comment by 3405691582** [comment]
Ah, I see the previous failing check run. I'll take a look.

**Comment by 3405691582** [comment]
This should be fixed now. The code state seemed to get reverted to an older state when I was trying to rebase and keep this up to date with HEAD. Please rerun checks.

**Comment by rnro** [comment]
The static Swift SDK tests are failing with issues like
```
[305/369] Compiling NIOPosix VsockAddress.swift
/swift-nio/Sources/NIOPosix/ControlMessage.swift:20:8: error: no such module 'Glibc'
 18 | #elseif os(Linux) || os(FreeBSD) || os(Android)
 19 | import CNIOLinux
 20 | import Glibc
    |        `- error: no such module 'Glibc'
 21 | #elseif os(OpenBSD)
 22 | import CNIOOpenBSD
```

**Comment by 3405691582** [comment]
> The static Swift SDK tests are failing

Fixed; caused by a typo. Sorry for the noise!

File: Sources/NIOConcurrencyHelpers/lock.swift [hunk 10]
```diff
@@ -52,6 +55,10 @@ public final class Lock {
     public init() {
         #if os(Windows)
         InitializeSRWLock(self.mutex)
+        #elseif os(OpenBSD)
+        var attr = pthread_mutexattr_t(bitPattern: 0)
+        let err = pthread_mutex_init(self.mutex, &attr)
```
Comment (kkebo) [inline Sources/NIOConcurrencyHelpers/lock.swift:60]: This `attr` is used before it's initialized. `pthread_mutexattr_init(&attr)` should be called before, right?

related: https://github.com/apple/swift-log/pull/387#issuecomment-3754770803

Comment (3405691582) [reply Sources/NIOConcurrencyHelpers/lock.swift:60]: Probably. I'll fix this in a new pr. Please at me if you're finding more incorrect usages on OpenBSD.

Comment (kkebo) [reply Sources/NIOConcurrencyHelpers/lock.swift:60]: I see. Thank you.
