### PR TITLE
Preserve getaddrinfo error code in SocketAddressError

### LINKED ISSUE #3382: getaddrinfo resolver throws away error code
NIO's default GAI resolver just throws away the error code and says `unknown(host:port:)`. That's not quite right, lots of reasons why GAI could fail, NIO should provide that info to the user

### PR DESCRIPTION
**Pull request by thisismanan**
As observed by @weissi https://github.com/apple/swift-nio/issues/3382                                                                                  
  ### Motivation:
  When `getaddrinfo` fails, SwiftNIO throws `SocketAddressError.unknown` which discards the error code. This makes it impossible for callers to
  distinguish between different failure reasons (e.g., `EAI_NONAME` vs `EAI_AGAIN`), which is needed for retry logic and diagnostics.                    
   
  ### Modifications:                                                                                                                                     
  - Add `SocketAddressError.UnknownHost` struct that carries `host`, `port`, `errorCode` (from `getaddrinfo`), and `errorDescription` (from
  `gai_strerror`).                                                                                                                                       
  - Update `SocketAddress.makeAddressResolvingHost` and `GetaddrinfoResolver` to throw/fail with the new error type on both POSIX and Windows paths.
  - Update existing test catch blocks to use the new error type.                                                                                         
  - Add `testGetaddrinfoErrorCodeIsPreserved` to verify the error code is captured.
                                                                                                                                                         
  ### Result:
  Callers can now inspect the `getaddrinfo` error code when host resolution fails, enabling more specific error handling. Resolves https://github.com/apple/swift-nio/issues/3382
  
### Questions for reviewer

   1. **Should `case unknown(host:port:)` be deprecated?** — This enum case is no longer thrown after this PR. Callers catching `.unknown` will silently stop matching. Should I add
    `@available(*, deprecated, renamed: "UnknownHost")` to provide a migration path?

   2. **Should the doc comment on `makeAddressResolvingHost` be updated?** — The `- Throws:` line still references `SocketAddressError.unknown` instead of the new
   `SocketAddressError.UnknownHost`.

### CODE REVIEW

**Comment by thisismanan** [comment]
Hey @Lukasa, just checking if you've had a chance to look at this. Happy to make any changes!

File: Sources/NIOCore/SocketAddresses.swift [hunk 1]
```diff
@@ -82,6 +83,27 @@ extension SocketAddressError {
             self.address = address
         }
     }
+
+    public struct UnknownHost: Error, Hashable, CustomStringConvertible {
+        public var host: String
+
+        public var port: Int
+
+        public var errorCode: CInt
```
Comment (simonjbeaumont) [inline Sources/NIOCore/SocketAddresses.swift]: We typically use plain `Int` in all public API, even when the range of values may be smaller.

```suggestion
        public var errorCode: Int
```

File: Sources/NIOCore/SocketAddresses.swift [hunk 2]
```diff
@@ -554,8 +581,14 @@ public enum SocketAddress: CustomStringConvertible, Sendable {
         var info: UnsafeMutablePointer<addrinfo>?
 
         // FIXME: this is blocking!
-        if getaddrinfo(host, String(port), nil, &info) != 0 {
-            throw SocketAddressError.unknown(host: host, port: port)
+        let rc = getaddrinfo(host, String(port), nil, &info)
+        if rc != 0 {
```
Comment (simonjbeaumont) [inline Sources/NIOCore/SocketAddresses.swift]: Nit: for check-condition-or-throw, we typically use a guard, which will also make this consistent with the three other places we have this pattern in this PR. Realise you were preserving what was already here, but we can make this change while we're here.

```suggestion
        guard rc == 0 else {
```

**Review by simonjbeaumont — CHANGES_REQUESTED** [review]
Thanks for this PR. Looks in pretty good shape to me. A few minor tweaks suggested.

To answer the open questions in your PR description...

> ### Questions for reviewer
> 1. **Should `case unknown(host:port:)` be deprecated?** — This enum case is no longer thrown after this PR. Callers catching `.unknown` will silently stop matching. Should I add
>    `@available(*, deprecated, renamed: "UnknownHost")` to provide a migration path?

I think that's a good idea. Not sure if the `renamed:` will provide the correct Fix-It since the replacement is not an enum case so a trivial source replacement may not be possible. Worth trying. If not, then a `message:` variant should be used.

> 2. **Should the doc comment on `makeAddressResolvingHost` be updated?** — The `- Throws:` line still references `SocketAddressError.unknown` instead of the new
>    `SocketAddressError.UnknownHost`.

Yes.

File: Sources/NIOCore/SocketAddresses.swift [hunk 3]
```diff
@@ -82,6 +83,27 @@ extension SocketAddressError {
...
+    public struct UnknownHost: Error, Hashable, CustomStringConvertible {
+        public var host: String
+
+        public var port: Int
+
+        public var errorCode: CInt
+
+        public var errorDescription: String
+
+        public init(host: String, port: Int, errorCode: CInt, errorDescription: String) {
```
Comment (simonjbeaumont) [inline Sources/NIOCore/SocketAddresses.swift]: Do we want people to be able to construct these in their own package? Can this be `package`?

File: Sources/NIOCore/SocketAddresses.swift (hunk 1 above)
Comment (thisismanan) [reply Sources/NIOCore/SocketAddresses.swift]: fixed this

File: Sources/NIOCore/SocketAddresses.swift (hunk 2 above)
Comment (thisismanan) [reply Sources/NIOCore/SocketAddresses.swift]: updated to guard for consistency, thank you!

File: Sources/NIOCore/SocketAddresses.swift (hunk 3 above)
Comment (thisismanan) [reply Sources/NIOCore/SocketAddresses.swift]: agreed, updated to `package`

**Review by simonjbeaumont — APPROVED** [review]
This LGTM. @weissi did you want to have a pass on this before it lands?

**Comment by thisismanan** [comment]
Hey @simonjbeaumont, Thanks for the review! Happy to wait for @weissi  to take a look if needed.
In the meantime — I noticed some test failures on the Linux nightly build. Could you help me understand if those are related to this PR or a known/pre-existing issue? Want to make sure I’m not holding things up if there’s something I should fix on my end.

**Comment by simonjbeaumont** [comment]
@thisismanan thanks for the ping. I think we'll just land this one. I had an offline discussion with @Lukasa who had no objections and, no: the nightly CI failures are not relevant here.
